name: Network Optimizer Speedtest
version: "1.6.5"
slug: network-optimizer-speedtest
description: OpenSpeedTest service for Network Optimizer
url: "https://github.com/LOOHP/home-assistant-apps"
arch:
- amd64
- aarch64
- armv7
- armhf
startup: services
boot: auto
init: false

ports:
  3000/tcp: 3005
ports_description:
  3000/tcp: OpenSpeedTest web UI

image: ghcr.io/ozark-connect/speedtest
