name: Network Optimizer
version: "1.10.0"
slug: network-optimizer
description: Run Ozark-Connect Network Optimizer
url: "https://github.com/LOOHP/home-assistant-apps"
arch:
- amd64
- aarch64
- armv7
- armhf
startup: services
boot: auto
init: false

host_network: true

map:
- type: share
  path: /app/data
  read_only: false
- type: ssl
  path: /app/ssh-keys
  read_only: false

image: ghcr.io/ozark-connect/network-optimizer

environment:
  Iperf3Server__Enabled: "true"
